#!/usr/bin/env python3
"""Simulates a production web server monitoring endpoint.

Reads a GitHub webhook JSON payload from stdin, resolves the local log file,
scans for known flaky patterns, and branches into one of two remediation paths:

  Scenario A (Flaky)  → Re-run the pipeline via the Actions API (ci_runner.py --fix)
  Scenario B (Hard)   → Open a mock GitHub Issue via the Core API (MOCK_GITHUB_ISSUES.md)
"""

import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ISSUES_FILE = os.path.join(SCRIPT_DIR, "MOCK_GITHUB_ISSUES.md")
FLAKY_PATTERN = re.compile(r"CRITICAL_DB_TIMEOUT")


def read_payload():
    raw = sys.stdin.read()
    if not raw.strip():
        print("[FATAL] No payload received on stdin. Aborting.")
        sys.exit(1)
    return json.loads(raw)


def resolve_log_path(payload):
    log_name = payload["workflow_run"]["mock_local_log"]
    return os.path.join(SCRIPT_DIR, log_name)


def scan_log(log_path):
    if not os.path.isfile(log_path):
        print(f"[WARN] Log file not found: {log_path}")
        return None
    with open(log_path) as f:
        return f.read()


def handle_flaky(payload):
    run_id = payload["workflow_run"]["id"]
    repo = payload["workflow_run"]["repository"]["full_name"]

    print(f"[Actions API Action] Flaky test detected! Triggering automatic pipeline re-run via Actions API...")
    print(f"  ↳ POST /repos/{repo}/actions/runs/{run_id}/rerun")
    print()

    result = subprocess.run(
        [sys.executable, os.path.join(SCRIPT_DIR, "ci_runner.py"), "--fix"],
        capture_output=False,
    )
    return result.returncode


def handle_hard_failure(payload, log_content):
    repo = payload["workflow_run"]["repository"]["full_name"]
    run_url = payload["workflow_run"]["html_url"]
    branch = payload["workflow_run"]["head_branch"]
    sha = payload["workflow_run"]["head_sha"][:7]
    run_id = payload["workflow_run"]["id"]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    print("[Core API Action] Hard bug detected! Opening a mock GitHub Issue ticket...")
    print(f"  ↳ POST /repos/{repo}/issues")
    print()

    # Extract error lines from the log
    error_lines = []
    if log_content:
        for line in log_content.splitlines():
            if "[ERROR]" in line:
                error_lines.append(line.strip())

    error_block = "\n".join(error_lines) if error_lines else "(no error lines captured)"

    issue_body = f"""
## 🐛 CI Pipeline Failure — Auto-Generated Issue

| Field | Value |
|-------|-------|
| **Repository** | `{repo}` |
| **Branch** | `{branch}` |
| **Commit** | `{sha}` |
| **Run ID** | `{run_id}` |
| **Run URL** | [{run_id}]({run_url}) |
| **Opened** | `{now}` |

### Captured Error Log

```
{error_block}
```

### Recommended Actions
- [ ] Investigate root cause in the failing test suite
- [ ] Check infrastructure dependencies (DB, cache, network)
- [ ] Re-run manually after fix: `gh run rerun {run_id}`

---
*Auto-generated by monitoring_controller.py via Core API simulation*
"""

    header_needed = not os.path.isfile(ISSUES_FILE)
    with open(ISSUES_FILE, "a") as f:
        if header_needed:
            f.write("# MOCK_GITHUB_ISSUES\n\n")
        f.write(issue_body)
        f.write("\n---\n\n")

    print(f"  ✓ Issue appended to {os.path.basename(ISSUES_FILE)}")


def main():
    print("=" * 60)
    print("Monitoring Controller  —  Webhook Receiver Endpoint")
    print("=" * 60)

    payload = read_payload()

    repo = payload["workflow_run"]["repository"]["full_name"]
    conclusion = payload["workflow_run"]["conclusion"]
    run_id = payload["workflow_run"]["id"]

    print(f"\n[RECV] Incoming webhook: workflow_run.{payload['action']}")
    print(f"  repo       = {repo}")
    print(f"  run_id     = {run_id}")
    print(f"  conclusion = {conclusion}")
    print()

    if conclusion != "failure":
        print("[INFO] Workflow succeeded. No action required.")
        sys.exit(0)

    # Simulate Actions API: download run logs
    log_path = resolve_log_path(payload)
    print(f"[Actions API] Downloading logs for run {run_id}...")
    print(f"  ↳ GET /repos/{repo}/actions/runs/{run_id}/logs")
    print(f"  ↳ (local) Reading {os.path.basename(log_path)}")
    print()

    log_content = scan_log(log_path)

    if log_content and FLAKY_PATTERN.search(log_content):
        print("[DIAGNOSIS] Error class: TRANSIENT / FLAKY")
        print()
        rc = handle_flaky(payload)
        if rc == 0:
            print("\n[RESULT] Re-run succeeded. Pipeline is green. ✓")
        else:
            print("\n[RESULT] Re-run also failed. Escalating to hard failure path.")
            handle_hard_failure(payload, log_content)
    else:
        print("[DIAGNOSIS] Error class: HARD / DETERMINISTIC")
        print()
        handle_hard_failure(payload, log_content)


if __name__ == "__main__":
    main()
